from db_classes import RunInformation, ConfigInformation, lgad_board_10ch_connections

runs_to_configs = {
    "Run001": "Config1",
    "Run002": "Config1",
    "Run003": "Config1",
    "Run004": "Config1",
    "Run005": "Config1",
    "Run006": "Config1",
    "Run007": "Config1",
    "Run008": "Config1",
    "Run009": "Config2",
    "Run010": "Config3",
    "Run011": "Config3",
    "Run012": "Config3",
    "Run013": "Config3",
    "Run014": "Config3",
    "Run015": "Config3",
    "Run016": "Config3",
    "Run017": "Config4",
    "Run018": "Config4",
    "Run019": "Config4a",
    "Run020": "Config4a",
    "Run021": "Config4a",
    "Run022": "Config4a",
    "Run023": "Config4a",
    "Run024": "Config4a",
    "Run025": "Config4a",
    "Run026": "Config4a",
    "Run027": "Config4a",
    "Run028": "Config4a",
    "Run029": "Config4a",
    "Run030": "Config4a",
    "Run031": "Config4a",
    "Run032": "Config4a",
    "Run033": "Config5",
    "Run034": "Config5",
    "Run035": "Config6",
    "Run036": "Config6",
    "Run037": "Config6",
    "Run038": "Config6",
    "Run039": "Config7",
    "Run040": "Config6",
    "Run041": "Config5",
    "Run042": "Config4a",
    "Run043": "Config8",
    "Run044": "Config8",
    "Run045": "Config9",
    "Run046": "Config10",
    "Run047": "Config12",
    "Run048": "Config12",
    "Run049": "Config12",
    "Run050": "Config13",
    "Run051": "Config14",
    "Run052": "Config14",
    "Run053": "Config14",
    "Run054": "Config14",
    "Run055": "Config14",
    "Run056": "Config14",
    "Run057": "Config14",
    "Run058": "Config14",
    "Run059": "Config14",
    "Run060": "Config14",
    "Run061": "Config14",
    "Run062": "Config14",
    "Run063": "Config14",
    "Run064": "Config14",
    "Run065": "Config14",
    "Run066": "Config14",
    "Run067": "Config14",
    "Run068": "Config14",
    "Run069": "Config14",
    "Run070": "Config14",
    "Run013_J" : "Config2_J",
    "Run016_J" : "Config3_J",
    "Run022_J" : "Config3_J"
}

run_config_info = {
    "Config3_J": ConfigInformation(
    name = "Config 3_J",
    board_order = ["PPS_LGAD_05", "PPS_LGAD_03"],  # left board (Image 1) is in front
    sensor_channels = lgad_board_10ch_connections,
    sampic_to_board = {
        "PPS_LGAD_03": {0: 10, 1: 9, 2: 8, 3: 7, 4: 6, 5: 5, 6: 4, 7: 3, 8: 2, 9: 1},
        "PPS_LGAD_05": {30: 10, 31: 9, 32: 8, 33: 7, 34: 6, 35: 5, 36: 4, 37: 3, 38: 2, 39: 1},
    },
    bias_voltage = {
        "PPS_LGAD_03": -230.0,
        "PPS_TILGAD_AIDA_01": -310.0,
    },
    power = {
        "ch1": 4.20,
        "ch2": 4.20,
    },
    power_connections = {
        "ch1": ("OA02", "OA05"),
        "ch2": ("OA01","OA04"),
    },
    sampic_amplifiers = {
        0: "OA02.8", 1: "OA02.7", 2: "OA02.6", 3: "OA02.5", 4: "OA02.4", 5: "OA02.3",
        6: "OA02.2", 7: "OA02.1", 8: "OA05.8", 9: "OA05.7", 10: "OA05.6", 11: "OA05.5",
        12: "OA05.4", 13: "OA05.3", 14: "OA05.2", 15: "OA01.1", 16: "OA01.8", 17: "OA01.7",
        18: "OA01.6", 19: "OA01.5", 20: "OA01.4", 21: "OA01.3", 22: "OA01.2", 23: "OA05.1",
        24: "OA04.8", 25: "OA04.7", 26: "OA04.6", 27: "OA04.5", 28: "OA04.4", 29: "OA04.3",
        30: "OA04.2", 31: "OA04.1", 32: "OA03.8", 33: "OA03.7", 34: "OA03.6", 35: "OA03.5",
        36: "OA03.4", 37: "OA03.3", 38: "OA03.2", 39: "OA03.1",
    },
    ),

    "Config2_J": ConfigInformation(
        name = "Config 2_J",
        board_order = ["PPS_TILGAD_AIDA_01", "PPS_LGAD_03"],  # left board (Image 1) is in front
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0: 10, 1: 9, 2: 8, 3: 7, 4: 6, 5: 5, 6: 4, 7: 3, 8: 2, 9: 1},
            "PPS_TILGAD_AIDA_01": {10: 10, 11: 9, 12: 8, 13: 7, 14: 6, 23: 5, 16: 4, 17: 3, 18: 2, 19: 1},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.50,
            "ch2": 4.50,
        },
        power_connections = {
            "ch1": ("OA02", "OA05"),
            "ch2": ("OA01",),
        },
        sampic_amplifiers = {
            0: "OA02.8", 1: "OA02.7", 2: "OA02.6", 3: "OA02.5", 4: "OA02.4",
            5: "OA02.3", 6: "OA02.2", 7: "OA02.1", 8: "OA05.8", 9: "OA05.7",
            10: "OA05.6", 11: "OA05.5", 12: "OA05.4", 13: "OA05.3", 14: "OA05.2",
            16: "OA01.8", 17: "OA01.7", 18: "OA01.6", 19: "OA01.5", 23: "OA05.1",
        },
    ),
    "Config1": ConfigInformation(
        name = "Config 1",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "LA01", "LA02", "LA05"),
            "ch2": ("CA04", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA05",
            9: "LA06",
        },
        flip=True
    ),
    "Config2": ConfigInformation(
        name = "Config 2",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {4:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 0:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "LA01", "LA02", "LA05"),
            "ch2": ("CA04", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA05",
            9: "LA06",
        },
        flip=True
    ),
    "Config3": ConfigInformation(
        name = "Config 3",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {4:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 0:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "LA01", "LA02", "LA05"),
            "ch2": ("CA04", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA05",
            9: "LA06",
        },
        flip=True
    ),
    "Config4": ConfigInformation(
        name = "Config 4",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "LA01", "LA02", "LA04"),
            "ch2": ("CA04", "CA05", "CA06", "LA05"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA04",
            9: "LA05",
        },
        flip=True
    ),
    "Config4a": ConfigInformation(
        name = "Config 4a",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "LA01", "LA02", "LA04"),
            "ch2": ("CA04", "CA05", "CA06", "LA05"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA04",
            9: "LA05",
        },
        flip=True
    ),
    "Config5": ConfigInformation(
        name = "Config 5",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "LA05", "CA03", "LA01", "LA02", "LA03"),
            "ch2": ("CA04", "CA05", "CA06", "LA04"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "LA05",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA03",
            9: "LA04",
        },
        flip=True
    ),
    "Config6": ConfigInformation(
        name = "Config 6",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:3, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:3},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "LA05", "CA03", "LA01", "LA02", "LA03"),
            "ch2": ("CA04", "CA05", "CA06", "LA04"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "LA05",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA03",
            9: "LA04",
        },
        flip=True
    ),
    "Config7": ConfigInformation(
        name = "Config 7",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "LA05", "CA03", "LA01", "LA02", "LA06"),
            "ch2": ("CA04", "CA05", "CA06", "LA03"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "LA05",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA06",
            9: "LA03",
        },
        flip=True
    ),
    "Config8": ConfigInformation(
        name = "Config 8",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA04", "LA01", "LA02", "LA05"),
            "ch2": ("CA03", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA04",
            3: "CA03",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "LA05",
            9: "LA06",
        },
        flip=True
    ),
    "Config9": ConfigInformation(
        name = "Config 9",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:1, 1:2, 2:8, 6:10, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:1, 8:9, 9:10},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "LA05", "CA04", "LA01", "LA02", "CA03"),
            "ch2": ("LA04", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "LA05",
            2: "CA04",
            3: "LA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "CA03",
            9: "LA06",
        },
        flip=True
    ),
    "Config10": ConfigInformation(
        name = "Config 10",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:3, 1:2, 2:8, 6:6, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:3, 8:9, 9:6},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("CA01", "LA05", "CA04", "LA01", "LA02", "CA03"),
            "ch2": ("LA04", "CA05", "CA06", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "LA05",
            2: "CA04",
            3: "LA04",
            4: "CA05",
            5: "CA06",
            6: "LA01",
            7: "LA02",
            8: "CA03",
            9: "LA06",
        },
        flip=True
    ),
    "Config11": ConfigInformation(
        name = "Config 11",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:3, 1:2, 2:8, 6:6, 7:9},
            "PPS_TILGAD_AIDA_01": {3:8, 4:2, 5:3, 8:9, 9:6},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.1,
            "ch2": 4.1,
        },
        power_connections = {
            "ch1": ("AA01", "AA02", "AA03", "AA04", "AA05"),
            "ch2": ("AA06", "AA07", "DA01", "AA09", "AA10"),
        },
        sampic_amplifiers = {
            0: "AA01",
            1: "AA02",
            2: "AA03",
            3: "AA04",
            4: "AA05",
            5: "AA06",
            6: "AA07",
            7: "DA01-20dB",
            8: "AA09",
            9: "AA10",
        },
        flip=True
    ),
    "Config12": ConfigInformation(
        name = "Config 12",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:9, 1:8, 2:3, 3:6, 4:2},
            "PPS_TILGAD_AIDA_01": {5:9, 6:8, 7:3, 8:6, 9:2},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.5,
            "ch2": 4.5,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "CA04", "CA05"),
            "ch2": ("LA01", "LA02", "LA03", "LA04", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA05",
            5: "LA01",
            6: "LA02",
            7: "LA03",
            8: "LA04",
            9: "LA06",
        },
        flip=True
    ),
    "Config13": ConfigInformation(
        name = "Config 13",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:9, 1:8, 2:3, 3:6, 4:2},
            "PPS_TILGAD_AIDA_01": {5:9, 6:8, 7:3, 8:6, 9:2},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.5,
            "ch2": 4.5,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "CA04", "CA06"),
            "ch2": ("LA01", "LA02", "LA03", "LA04", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            4: "CA06",
            5: "LA01",
            6: "LA02",
            7: "LA03",
            8: "LA04",
            9: "LA06",
        },
        flip=True
    ),
    "Config14": ConfigInformation(
        name = "Config 14",
        board_order = ["PPS_LGAD_03", "PPS_TILGAD_AIDA_01"],
        sensor_channels = lgad_board_10ch_connections,
        sampic_to_board = {
            "PPS_LGAD_03": {0:9, 1:8, 2:3, 3:6, 11:2},
            "PPS_TILGAD_AIDA_01": {5:9, 6:8, 7:3, 8:6, 9:2},
        },
        bias_voltage = {
            "PPS_LGAD_03": -230.0,
            "PPS_TILGAD_AIDA_01": -200.0,
        },
        power = {
            "ch1": 4.5,
            "ch2": 4.5,
        },
        power_connections = {
            "ch1": ("CA01", "CA02", "CA03", "CA04", "CA06"),
            "ch2": ("LA01", "LA02", "LA03", "LA04", "LA06"),
        },
        sampic_amplifiers = {
            0: "CA01",
            1: "CA02",
            2: "CA03",
            3: "CA04",
            11: "CA06",
            5: "LA01",
            6: "LA02",
            7: "LA03",
            8: "LA04",
            9: "LA06",
        },
        flip=True
    ),
}

run_info = {
    "Run016_J": RunInformation(
        name = "Run 016_J",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 23),
        data_format = "binary",
        comment = "Config3_J. First run with normal LGAD and Irradiated LGAD, the other Irradiated LGAD does not have a functioning power supply yet (issues with GPIB communication).",
    ),
    "Run022_J": RunInformation(
        name = "Run 022_J",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 23),
        data_format = "binary",
        comment = "Config3_J. New run after stop for magnet intervention.",
    ),
    "Run013_J": RunInformation(
        name = "Run 013_J",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 23),
        data_format = "binary",
        comment = "Config2_J. Rebuild configuration with 0.220V CFD baseline.",
    ),
    "Run001": RunInformation(
        name = "Run 001",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "First run, very short, for testing binary unpacking",
    ),
    "Run002": RunInformation(
        name = "Run 002",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Short run with a little bit more statistics, still for unpacking",
    ),
    "Run003": RunInformation(
        name = "Run 003",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "First long overnight run with output saved to multiple files",
    ),
    "Run004": RunInformation(
        name = "Run 004",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "ascii",
        comment = "Short run saved in ASCII format in order to understand the data format",
    ),
    "Run005": RunInformation(
        name = "Run 005",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Medium run, with the threshold of the 'noisy channel' (channel 8) adjusted",
    ),
    "Run006": RunInformation(
        name = "Run 006",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Short run for testing new threshold",
    ),
    "Run007": RunInformation(
        name = "Run 007",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "ascii",
        comment = "Run split into multiple files with ASCII output to help understand data format",
    ),
    "Run008": RunInformation(
        name = "Run 008",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Overnight run with the new threshold settings",
    ),
    "Run009": RunInformation(
        name = "Run 009",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run010": RunInformation(
        name = "Run 010",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V372,H272: ~600 hits/spill",
    ),
    "Run011": RunInformation(
        name = "Run 011",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V372,H274: ~720 hits/spill",
    ),
    "Run012": RunInformation(
        name = "Run 012",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V372,H276: ~570 hits/spill",
    ),
    "Run013": RunInformation(
        name = "Run 013",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V374,H274: ~2000 hits/spill",
    ),
    "Run014": RunInformation(
        name = "Run 014",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V376,H274: ~2300 hits/spill",
    ),
    "Run015": RunInformation(
        name = "Run 015",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Stage position V378,H274: ~1800 hits/spill",
    ),
    "Run016": RunInformation(
        name = "Run 016",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Long run at final position, Stage position V376,H274",
    ),
    "Run017": RunInformation(
        name = "Run 017",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Started the run immediately after moving connections, but forgot to retune thresholds for new amplifier so SAMPIC channel 8 was a bit noisy in terms of triggering on the baseline",
    ),
    "Run018": RunInformation(
        name = "Run 018",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Retuned thresholds, in particular for the swapped channels, but reduced a bit for a few other channels too since they were a bit high previously",
    ),
    "Run019": RunInformation(
        name = "Run 019",
        trigger_mode = "self",
        trigger_channels = (0),
        data_format = "binary",
        comment = "SAMPIC Channel 0, threshold set to 7𝑚𝑉, threshold returned to 14𝑚𝑉 after the run",
    ),
    "Run020": RunInformation(
        name = "Run 020",
        trigger_mode = "self",
        trigger_channels = (1),
        data_format = "binary",
        comment = "SAMPIC Channel 1, threshold set to 8𝑚𝑉, threshold returned to 14𝑚𝑉 after the run",
    ),
    "Run021": RunInformation(
        name = "Run 021",
        trigger_mode = "self",
        trigger_channels = (2),
        data_format = "binary",
        comment = "SAMPIC Channel 2, threshold set to 2𝑚𝑉, threshold returned to 6𝑚𝑉 after the run",
    ),
    "Run022": RunInformation(
        name = "Run 022",
        trigger_mode = "self",
        trigger_channels = (3),
        data_format = "binary",
        comment = "SAMPIC Channel 3, threshold set to 10𝑚𝑉, threshold returned to 12𝑚𝑉 after the run",
    ),
    "Run023": RunInformation(
        name = "Run 023",
        trigger_mode = "self",
        trigger_channels = (4),
        data_format = "binary",
        comment = "SAMPIC Channel 4, threshold set to 10𝑚𝑉, due to some weird effect (ringing?) will perform a scan of threshold to see different behaviours",
    ),
    "Run024": RunInformation(
        name = "Run 024",
        trigger_mode = "self",
        trigger_channels = (4),
        data_format = "binary",
        comment = "SAMPIC Channel 4, threshold set to 15𝑚𝑉",
    ),
    "Run025": RunInformation(
        name = "Run 025",
        trigger_mode = "self",
        trigger_channels = (4),
        data_format = "binary",
        comment = "SAMPIC Channel 4, threshold set to 20𝑚𝑉",
    ),
    "Run026": RunInformation(
        name = "Run 026",
        trigger_mode = "self",
        trigger_channels = (4),
        data_format = "binary",
        comment = "SAMPIC Channel 4, threshold set to 25𝑚𝑉",
    ),
    "Run027": RunInformation(
        name = "Run 027",
        trigger_mode = "self",
        trigger_channels = (4),
        data_format = "binary",
        comment = "SAMPIC Channel 4, threshold set to 30𝑚𝑉, threshold returned to 33𝑚𝑉 after the run",
    ),
    "Run028": RunInformation(
        name = "Run 028",
        trigger_mode = "central",
        trigger_channels = (2),
        data_format = "binary",
        comment = "Trigger on SAMPIC Channel 2 with threshold 2𝑚𝑉 but readout all channels",
    ),
    "Run029": RunInformation(
        name = "Run 029",
        trigger_mode = "central",
        trigger_channels = (1),
        data_format = "binary",
        comment = "Trigger on SAMPIC Channel 1 with threshold 8𝑚𝑉 but readout all channels",
    ),
    "Run030": RunInformation(
        name = "Run 030",
        trigger_mode = "central",
        trigger_channels = (1),
        data_format = "ascii",
        comment = "Same config as Run029 but with ASCII output in order to evaluate the format",
    ),
    "Run031": RunInformation(
        name = "Run 031",
        trigger_mode = "central",
        trigger_channels = (2),
        data_format = "ascii",
        comment = "Same config as Run028 but with ASCII output in order to evaluate the format",
    ),
    "Run032": RunInformation(
        name = "Run 032",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Beam is back. Returned all channels to normal thresholds and used the central trigger, allowing any 1 channel to trigger the readout of all channels. Configuration is effectively the same as Run018 but with the new central trigger functionality",
    ),
    "Run033": RunInformation(
        name = "Run 033",
        trigger_mode = "central",
        trigger_channels = (0, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "When tuning the threshold for SAMPIC channel 1, there seemed to be a lot of noise/oscillation which required setting the trigger threshold to an extremely large value, 140𝑚𝑉. Consequently, SAMPIC channel 1 was not included in the central trigger, but was readout.",
    ),
    "Run034": RunInformation(
        name = "Run 034",
        trigger_mode = "central",
        trigger_channels = (0, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Retuned the thresholds of a couple of channels, since in the previous run it seemed like there were considerable triggers on noise",
    ),
    "Run035": RunInformation(
        name = "Run 035",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run036": RunInformation(
        name = "Run 036",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run037": RunInformation(
        name = "Run 037",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run038": RunInformation(
        name = "Run 038",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run039": RunInformation(
        name = "Run 039",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run040": RunInformation(
        name = "Run 040",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Data recovery run",
    ),
    "Run041": RunInformation(
        name = "Run 041",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Data recovery run",
    ),
    "Run042": RunInformation(
        name = "Run 042",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Data recovery run, unlike the previous runs, this one uses the central trigger mechanism",
    ),
    "Run043": RunInformation(
        name = "Run 043",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Several channels became significantly more noisy (in amplitude) during the run, the amount of useful data is uncertain, there may not be much but there is certainly some at the start",
    ),
    "Run044": RunInformation(
        name = "Run 044",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        comment = "Retuned the thresholds to handle the increased noise",
    ),
    "Run045": RunInformation(
        name = "Run 045",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run046": RunInformation(
        name = "Run 046",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
    ),
    "Run047": RunInformation(
        name = "Run 047",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 7,
            3: 19,
            4: 65,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
        },
    ),
    "Run048": RunInformation(
        name = "Run 048",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 7,
            3: 19,
            4: 65,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
        },
        comment = "Tuned thresholds",
    ),
    "Run049": RunInformation(
        name = "Run 049",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 7,
            3: 19,
            4: 65,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
        },
        comment = "Self trigger",
    ),
    "Run050": RunInformation(
        name = "Run 050",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 9,
            3: 19,
            4: 70,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
        },
        comment = "Self trigger",
    ),
    "Run051": RunInformation(
        name = "Run 051",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 5, 6, 7, 8, 9, 11),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 9,
            3: 19,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
            11: 72,
        },
        comment = "Self trigger",
    ),
    "Run052": RunInformation(
        name = "Run 052",
        trigger_mode = "central",
        trigger_channels = (11),
        data_format = "binary",
        thresholds = {
            11: 72,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 11",
    ),
    "Run053": RunInformation(
        name = "Run 053",
        trigger_mode = "central",
        trigger_channels = (9),
        data_format = "binary",
        thresholds = {
            9: 28,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 9",
    ),
    "Run054": RunInformation(
        name = "Run 054",
        trigger_mode = "central",
        trigger_channels = (8),
        data_format = "binary",
        thresholds = {
            8: 20,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 8",
    ),
    "Run055": RunInformation(
        name = "Run 055",
        trigger_mode = "central",
        trigger_channels = (7),
        data_format = "binary",
        thresholds = {
            7: 13,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 7",
    ),
    "Run056": RunInformation(
        name = "Run 056",
        trigger_mode = "central",
        trigger_channels = (6),
        data_format = "binary",
        thresholds = {
            6: 12,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 6: High rate",
    ),
    "Run057": RunInformation(
        name = "Run 057",
        trigger_mode = "central",
        trigger_channels = (5),
        data_format = "binary",
        thresholds = {
            5: 14,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 5: Very high rate",
    ),
    "Run058": RunInformation(
        name = "Run 058",
        trigger_mode = "central",
        trigger_channels = (3),
        data_format = "binary",
        thresholds = {
            3: 19,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 3: Maybe coincidence with ch 5",
    ),
    "Run059": RunInformation(
        name = "Run 059",
        trigger_mode = "central",
        trigger_channels = (2),
        data_format = "binary",
        thresholds = {
            2: 9,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 2: Maybe coincidence with ch 6",
    ),
    "Run060": RunInformation(
        name = "Run 060",
        trigger_mode = "central",
        trigger_channels = (1),
        data_format = "binary",
        thresholds = {
            1: 7,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 1: High rate; Coincidence with ch 6",
    ),
    "Run061": RunInformation(
        name = "Run 061",
        trigger_mode = "central",
        trigger_channels = (0),
        data_format = "binary",
        thresholds = {
            0: 18,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 0: Extremely high rate",
    ),
    "Run062": RunInformation(
        name = "Run 062",
        trigger_mode = "central",
        trigger_channels = (11),
        data_format = "binary",
        thresholds = {
            11: 72,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 11: Maybe coincidence with 5",
    ),
    "Run063": RunInformation(
        name = "Run 063",
        trigger_mode = "central-2hits",
        trigger_channels = (0, 5),
        data_format = "binary",
        thresholds = {
            0: 18,
            5: 14,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 0 or ch 5 and require 2 hits",
    ),
    "Run064": RunInformation(
        name = "Run 064",
        trigger_mode = "central-2hits",
        trigger_channels = (11, 5),
        data_format = "binary",
        thresholds = {
            5: 14,
            11: 72,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 11 or ch 5 and require 2 hits",
    ),
    "Run065": RunInformation(
        name = "Run 065",
        trigger_mode = "central-2hits",
        trigger_channels = (1, 5),
        data_format = "binary",
        thresholds = {
            1: 7,
            5: 14,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 1 or ch 5 and require 2 hits",
    ),
    "Run066": RunInformation(
        name = "Run 066",
        trigger_mode = "central-2hits",
        trigger_channels = (3, 5),
        data_format = "binary",
        thresholds = {
            3: 19,
            5: 14,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 3 or ch 5 and require 2 hits",
    ),
    "Run067": RunInformation(
        name = "Run 067",
        trigger_mode = "central-2hits",
        trigger_channels = (1, 6),
        data_format = "binary",
        thresholds = {
            1: 7,
            6: 12,
        },
        comment = "Central trigger but only trigger on SAMPIC ch 1 or ch 6 and require 2 hits",
    ),
    "Run068": RunInformation(
        name = "Run 068",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 5, 6, 7, 8, 9, 11),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 9,
            3: 19,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
            11: 72,
        },
        comment = "Central trigger any single channel can trigger",
    ),
    "Run069": RunInformation(
        name = "Run 069",
        trigger_mode = "self",
        trigger_channels = (0, 1, 2, 3, 5, 6, 7, 8, 9, 11),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 9,
            3: 19,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
            11: 72,
        },
        comment = "Self trigger",
    ),
    "Run070": RunInformation(
        name = "Run 070",
        trigger_mode = "central",
        trigger_channels = (0, 1, 2, 3, 5, 6, 7, 8, 9, 11),
        data_format = "binary",
        thresholds = {
            0: 18,
            1: 7,
            2: 9,
            3: 19,
            5: 14,
            6: 12,
            7: 13,
            8: 20,
            9: 28,
            11: 72,
        },
        comment = "Central trigger any single channel can trigger",
    ),
}

config_info = {}